import type { Metadata } from "next";
import { Rubik, Rakkas } from "next/font/google";
import "./globals.css";
import Header from "@/layout/Header";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const rakkas = Rakkas({
  variable: "--font-rakkas",
  subsets: ["arabic"],
  weight: "400",
});
export const metadata: Metadata = {
  title: " نور الهدى ",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${rubik.variable} ${rakkas.variable}`}>
      <body className={`antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
